[main]
path = "datasets/"
project_name = "batch_testing"
project_ref = ".."

[pheno]
dataset_path='pheno.dta'
modeltype='basic_pk'
administration='iv'
cl_init=0.01
vc_init=1.0
search_space='COVARIATE?(@IIV,[APGR,FA1,FA2],CAT)'
allometric_variable='WGT'

[moxo_pk]
dataset_path='moxonidine_pk.csv'
modeltype='basic_pk'
administration='oral'
cl_init=30.0
vc_init=100.0
mat_init=0.3
allometric_variable='WT'
occasion='VISI'
search_space='LET(CATEGORICAL,[SEX,NYHA,COMP,ACE,DIG,DIU]);LET(CONTINUOUS,[AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL,CAT)'

